# Generated by Django 3.1 on 2020-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('политика', 'Политика'), ('общество', 'Общество'), ('дополнительно', 'Дополнительно')], default='дополнительно', max_length=20),
        ),
    ]
